### PR TITLE
exampleSite: fix editURL

### PR DESCRIPTION
**Pull request by Nuc1eoN**
This fixes the edit url button on your example site.

### CODE REVIEW

**Comment by McShelby** [comment]
I explicitly removed this as I saw double // in my test. Weird.

**Comment by Nuc1eoN** [comment]
>I explicitly removed this as I saw double // in my test. Weird.

@McShelby if you add a trainling "/"  to `baseURL=` that will happen. Maybe you mixed it up.

**Comment by Nuc1eoN** [comment]
Huh, wait a second actually I was wrong about the `baseURL` thing.

So for me the trailing / is needed, but I have just noticed that when I go to GoboLinux Wiki home (try my repo version), and I press the "Edit" button it will redirect with `content//_index.md`, however it will still work. On the other pages I do not see this, weird.

**Comment by McShelby** [comment]
Yeah, I noticed this also. Nevertheless, better keep the double // as it doesn't break a thing

**Pull request merged**
