### PR TITLE
Add the Dynamic Collapsible Tree Menu support

### PR DESCRIPTION
**Pull request by poad**
Added an option to allow the menu in the sidebar (the tree of topics) to be displayed collapsibly.

This is the content of a pull request https://github.com/matcornic/hugo-theme-learn/pull/526 issued to matcornic/hugo-theme-learn.

CSS, input[type=checkbox] tag, and label tag are used to dynamically open and close the menu tree.

## examples

<http://hugo-theme-relearn-examples.s3-website-ap-northeast-1.amazonaws.com>

### source

<https://github.com/poad/hugo-relearn-example>

### CODE REVIEW

**Comment by McShelby** [comment]
At first: Thanks @poad for your submission.

Before commenting on the implementation, what issue or UX inconvenience does this PR solves? At the moment I am not to keen to merge this as I don't see the gain for the majority of users.

This point of view may also come from some issues with your implementation.

- If a submenu is expanded, it shouldn't add just another scrollbar for that section, but should expand using the whole available menu space as with the current implementation.

  Because of the scrollbar, the overall design lacks, as the background of the currently viewn menu topic does not blend with the content background.

  Also because of the scrollbar, no menu topics are visible on low resolution screens.

- Indention on parent topics is off. As you can see in your example with the "Children" shortcode topic.

**Comment by poad** [comment]
Dear @McShelby 

Thanks for checking out this PR.

I'll answer your questions.

Expanding the entire submenu requires scrolling when the tree is large, which makes the menu difficult to use in some environments.

Currently, without this feature, we try to display the tree up to one level below the hierarchy we are viewing.

This leaves us with the problem of not knowing how many levels of descendant submenus exist.

To solve these problems, we want to make it dynamically collapsible.

**Comment by poad** [comment]
By the way, the document in question is a private document, so it cannot be published.

My team is considering either introducing an implementation or switching to a different theme for this feature.

I have personally submited this PR because I think I should contribute to the development of OSS since I am allowed to use it.

**Comment by McShelby** [comment]
See #231

**Comment by McShelby** [comment]
Thanks for submission. I've used your patch as a starting point to implement #231.

In the final implementation I've simplified the CSS and fixed some issues when hidden sections are involved.

**Comment by McShelby** [comment]
Btw: You can see this in action on the official documentation site.

Also, I've fixed the scrollbar issues that I've mentioned earlier

**Pull request closed without merging**
