### PR TITLE
feat: update mermaid to 10.3.0

### PR DESCRIPTION
**Pull request by nexeck**
fixes: #601

### CODE REVIEW

**Comment by nexeck** [comment]
Needs more work, sankey isn't working.

**Comment by McShelby** [comment]
Please add a sankey example taken from the Mermaid docs into the Themes Mermaid page.

**Comment by nexeck** [comment]
MermaidJS is deprecating the support for directives for all new stuff.
https://github.com/mermaid-js/mermaid/issues/4630#issuecomment-1641521124

**Comment by McShelby** [comment]
Well. Mermaid becomes a mess in my opinion but my impression might come from a lack of communication.

Anyways I will not add workarounds nor a half working Mermaid version to the release until mermaid-js/mermaid#4630 is closed and a clear alternative is announced.

**Comment by nexeck** [comment]
> Well. Mermaid becomes a mess in my opinion but my impression might come from a lack of communication.
> 
> Anyways I will not add workarounds nor a half working Mermaid version to the release until [mermaid-js/mermaid#4630](https://github.com/mermaid-js/mermaid/issues/4630) is closed and a clear alternative is announced.

The alternative seems to be the yaml style config: https://github.com/mermaid-js/mermaid/issues/4630#issuecomment-1641521124

I added a workaround which should not break compatibility with existing diagrams.

When the original diagram has no directive, its adding the default theme as yaml config, if the diagram has a directive, it adds the theme, when its missing like before this PR.

**Comment by McShelby** [comment]
The sankey graph currently break in this PR if the theme variant is switched from Relearn Light to Relearn Dark.

Also the generated empty JSON inside of YAML looks suspicious to me:

````
---
{}
---
%%{init: {"fontFamily":"monospace","sequence":{"showSequenceNumbers":true},"theme":"dark"}}%%
sequenceDiagram
    Alice->>John: Hello John, how are you?
    loop Healthcheck
````

**Comment by nexeck** [comment]
Thanks for the feedback, i will look into this next week.

**Comment by nexeck** [comment]
> The sankey graph currently breaks in this PR if the theme variant is switched from Relearn Light to Relearn Dark.
> 
> Also the generated empty JSON inside of YAML looks suspicious to me:
> 
> ```
> ---
> {}
> ---
> %%{init: {"fontFamily":"monospace","sequence":{"showSequenceNumbers":true},"theme":"dark"}}%%
> sequenceDiagram
>     Alice->>John: Hello John, how are you?
>     loop Healthcheck
> ```

Both should be fixed now. And now i understand, what you mean with mermaidJS is a mess.

**Comment by McShelby** [comment]
Thanks for working on this.

It still did not work, because the theme setting will always be written to the `dir` (directive) object which does not work with the sankey graph. I've fixed this and some minor stuff.

Could you confirm that it works for your test cases.

**Comment by nexeck** [comment]
> Thanks for working on this.
> 
> It still did not work, because the theme setting will always be written to the `dir` (directive) object which does not work with the sankey graph. I've fixed this and some minor stuff.
> 
> Could you confirm that it works for your test cases.

Works for me, thanks.

**Pull request merged**
